export type CaptionToken = {
  text: string;          // Hinglish (Roman script) — what gets rendered
  devanagari?: string;   // original Devanagari word (kept for debugging/merges)
  startMs: number;
  endMs: number;
};

// One karaoke "page": 3-4 words shown on a single line, active word highlighted.
// Times are on the GLOBAL timeline (scene offsets already applied by the
// Python side, agent/remotion_render.py).
export type CaptionPage = {
  text: string;
  startMs: number;
  endMs: number;
  tokens: CaptionToken[];
};

// ─── Data-driven popup / icon overlays (generated by scripts/popup_designer.py) ──
export type PopupIcon =
  | { type: 'emoji'; value: string }        // "🤖"
  | { type: 'simpleicon'; value: string }   // simple-icons slug: "openai"
  | { type: 'svg'; value: string };         // curated ICONS key: "robot"

export type PopupCard = {
  icon: PopupIcon;
  label: string;
  sub?: string;
  color: string;                            // "#RRGGBB"
  atMs: number;                             // scene-local ms — synced to spoken word
  slot: 'left' | 'center' | 'right';
  accent?: boolean;                         // hero card (stronger glow/border)
};

export type PopupSfx = { atMs: number; key: string; volume?: number };

export type PopupConfig = { cards: PopupCard[]; sfx: PopupSfx[] };

export type SceneClip = {
  index: number;
  brollSrc: string;      // path to B-roll relative to public
  brollSrc2?: string;    // optional 2nd B-roll (plays after brollSrc within the scene)
  avatarSrc: string;     // path to avatar relative to public
  durationInFrames: number;
  playbackRate?: number;
  popup?: PopupConfig;   // story-matched icon overlays for this scene
};

export type DocumentaryProps = {
  fps: number;
  width: number;
  height: number;
  scenes: SceneClip[];
  pages: CaptionPage[];
  style: {
    gold: string;
    captionColor: string;
    transition?: 'crossfade' | 'zoom-dissolve' | 'slide' | 'none';
    overlapFrames?: number;
  };
};
